spring:
  application:
    name: config-Server
  profiles:
    active: native
#  security:
#    user:
#      name: user1
#      password: password1
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888